title: Nick Zhong
subtitle: subtitle
description: description
avatarTitle: avatar title
avatarDesc: avatar description
url: url

# Comment
comment:
    provider: provider
    duoshuo:
    short_name: short_name

# Social
social:
    github: github
    mail: mail


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/MengZheK/kangblog.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


# permalink: /:year/:month/:title/

permalink: /:short_year:i_month:i_day.html
# 伪 postid 的方案,便于网站 SEO


# Format

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: title

# Navigation buttons in the front page.s
nav:
    - {title: archive, description: archive, url: '/archive'}   
    - {title: tags, description: tags, url: '/tags'}   
    - {title: about, description: about, url: '/about'}

          
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"
